[package]
name = "ohnomore-utils"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
conllu = "0.5.1"
getopts = "0.2"
ohnomore = { path = "../ohnomore" }
stdinout = "0.4"
