[package]
name = "ohnomore-utils"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
conllx = { git = "https://github.com/danieldk/conllx-rs" }
failure = "0.1"
getopts = "0.2"
ohnomore = { path = "../ohnomore" }
petgraph = "0.4"
stdinout = "0.4"
