[package]
name = "ohnomore"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
error-chain = "0.11"
fst = "0.3"
itertools = "0.7"
lazy_static = "1.0"
maplit = "1.0"
petgraph = "0.4"
serde = "1.0"
serde_derive = "1.0"
tensorflow = { git = "https://github.com/tensorflow/rust" }

[dev-dependencies]
quickcheck = "0.5"