[package]
name = "ohnomore"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
conllx = { git = "https://github.com/danieldk/conllx-rs" }
error-chain = "0.11"
fst = "0.3"
lazy_static = "1.0"
maplit = "1.0"
petgraph = "0.4"

[dev-dependencies]
quickcheck = "0.5"